import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { AppScreen } from '@/components/app-screen';
import { colors, fonts, radii, shadows, spacing } from '@/constants/design';
import { getActivity, type ActivityCategory, type ActivityEvent } from '@/features/actividad/api';
import { formatMoneyText } from '@/utils/money';

type CategoryFilter = 'TODOS' | ActivityCategory;
const categories: { value: CategoryFilter; label: string; icon: React.ComponentProps<typeof Ionicons>['name'] }[] = [
  { value: 'TODOS', label: 'Todos', icon: 'layers-outline' }, { value: 'COBRO', label: 'Cobros', icon: 'cash-outline' },
  { value: 'PRESTAMO', label: 'Préstamos', icon: 'wallet-outline' }, { value: 'RENOVACION', label: 'Renovaciones', icon: 'refresh-outline' },
  { value: 'CIERRE', label: 'Cierres', icon: 'shield-outline' },
  { value: 'CAJA', label: 'Caja', icon: 'business-outline' },
];
const media = ['TODOS', 'EFECTIVO', 'YAPE', 'PLIN', 'TRANSFERENCIA', 'OTRO'] as const;
type MediumFilter = typeof media[number];

export default function ActivityScreen() {
  const activityQuery = useQuery({ queryKey: ['actividad'], queryFn: getActivity });
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState<CategoryFilter>('TODOS');
  const [medium, setMedium] = useState<MediumFilter>('TODOS');
  const filtered = useMemo(() => {
    const term = normalize(search);
    return (activityQuery.data?.eventos ?? []).filter((event) => {
      const haystack = normalize([eventTitle(event), event.cliente_nombre, event.medio, event.nota].filter(Boolean).join(' '));
      return (category === 'TODOS' || event.categoria === category) && (medium === 'TODOS' || event.medio === medium) && (!term || haystack.includes(term));
    });
  }, [activityQuery.data?.eventos, category, medium, search]);
  const groups = useMemo(() => groupEvents(filtered), [filtered]);
  const filtersActive = category !== 'TODOS' || medium !== 'TODOS' || search.trim().length > 0;
  function clearFilters() { setSearch(''); setCategory('TODOS'); setMedium('TODOS'); }

  return <AppScreen title="Actividad" subtitle="Cada movimiento, conectado y verificable">
    <View style={styles.hero}><View style={styles.heroIcon}><Ionicons color="#FFFFFF" name="shield-checkmark" size={24} /></View><View style={styles.heroCopy}><Text style={styles.heroEyebrow}>TRAZABILIDAD COMPLETA</Text><Text style={styles.heroTitle}>Tu historia financiera</Text><Text style={styles.heroText}>Los reversos corrigen; ningún movimiento desaparece.</Text></View><View style={styles.heroCount}><Text style={styles.heroCountValue}>{activityQuery.data?.cantidad ?? 0}</Text><Text style={styles.heroCountLabel}>eventos</Text></View></View>
    <View style={styles.controls}>
      <View style={styles.searchBox}><Ionicons color={colors.textMuted} name="search-outline" size={19} /><TextInput accessibilityLabel="Buscar actividad" onChangeText={setSearch} placeholder="Buscar cliente, medio o movimiento" placeholderTextColor={colors.textMuted} returnKeyType="search" style={styles.searchInput} value={search} />{search ? <Pressable accessibilityLabel="Limpiar búsqueda" onPress={() => setSearch('')} style={styles.clearSearch}><Ionicons color={colors.textMuted} name="close-circle" size={18} /></Pressable> : null}</View>
      <ScrollView contentContainerStyle={styles.chips} horizontal showsHorizontalScrollIndicator={false}>{categories.map((item) => { const active = category === item.value; return <Pressable key={item.value} onPress={() => setCategory(item.value)} style={[styles.categoryChip, active && styles.categoryChipActive]}><Ionicons color={active ? '#FFFFFF' : colors.textSecondary} name={item.icon} size={15} /><Text style={[styles.categoryText, active && styles.categoryTextActive]}>{item.label}</Text></Pressable>; })}</ScrollView>
      <View style={styles.mediumRow}><Text style={styles.mediumLabel}>Medio</Text><ScrollView contentContainerStyle={styles.mediumChips} horizontal showsHorizontalScrollIndicator={false}>{media.map((item) => { const active = medium === item; return <Pressable key={item} onPress={() => setMedium(item)} style={[styles.mediumChip, active && styles.mediumChipActive]}><Text style={[styles.mediumText, active && styles.mediumTextActive]}>{item === 'TODOS' ? 'Todos' : titleCase(item)}</Text></Pressable>; })}</ScrollView></View>
    </View>
    {activityQuery.isPending ? <View style={styles.state}><ActivityIndicator color={colors.primary} size="large" /><Text style={styles.stateText}>Ordenando tu historial…</Text></View> : null}
    {activityQuery.isError ? <View style={styles.state}><View style={[styles.stateIcon, styles.errorIcon]}><Ionicons color={colors.danger} name="cloud-offline-outline" size={28} /></View><Text style={styles.stateTitle}>No pudimos cargar la actividad</Text><Text style={styles.stateText}>{activityQuery.error.message}</Text><Pressable onPress={() => activityQuery.refetch()} style={styles.retryButton}><Text style={styles.retryText}>Reintentar</Text></Pressable></View> : null}
    {activityQuery.isSuccess && groups.map((group) => <View key={group.key} style={styles.group}><View style={styles.groupHeader}><Text style={styles.groupTitle}>{group.label}</Text><Text style={styles.groupCount}>{group.events.length} {group.events.length === 1 ? 'movimiento' : 'movimientos'}</Text></View><View style={styles.timeline}>{group.events.map((event, index) => <ActivityRow event={event} isLast={index === group.events.length - 1} key={`${event.tipo}-${event.id}`} />)}</View></View>)}
    {activityQuery.isSuccess && filtered.length === 0 ? <View style={styles.state}><View style={styles.stateIcon}><Ionicons color={colors.primary} name={filtersActive ? 'search-outline' : 'receipt-outline'} size={28} /></View><Text style={styles.stateTitle}>{filtersActive ? 'No encontramos coincidencias' : 'Tu historial está listo para empezar'}</Text><Text style={styles.stateText}>{filtersActive ? 'Prueba con otro cliente, medio o tipo de movimiento.' : 'Los préstamos, pagos y movimientos de Caja aparecerán aquí automáticamente.'}</Text>{filtersActive ? <Pressable onPress={clearFilters} style={styles.retryButton}><Text style={styles.retryText}>Limpiar filtros</Text></Pressable> : null}</View> : null}
    {activityQuery.isSuccess && filtered.length > 0 ? <View style={styles.end}><View style={styles.endLine} /><View style={styles.endIcon}><Ionicons color={colors.textMuted} name="lock-closed-outline" size={14} /></View><View style={styles.endLine} /></View> : null}
  </AppScreen>;
}

function ActivityRow({ event, isLast }: { event: ActivityEvent; isLast: boolean }) {
  const visual = eventVisual(event); const canOpen = Boolean(event.prestamo_id);
  const date = new Intl.DateTimeFormat('es-PE', { hour: 'numeric', minute: '2-digit' }).format(new Date(event.ocurrido_at));
  const isLoan = event.tipo === 'RENOVACION' || event.tipo === 'PRESTAMO_CREADO';
  const isClosure = event.tipo === 'PRESTAMO_INCOBRABLE' || event.tipo === 'PRESTAMO_ANULADO';
  const mainAmount = isLoan ? event.monto_base ?? event.monto : event.monto;
  const sign = isLoan || isClosure ? '' : event.direccion === 1 ? '+ ' : '− ';
  return <Pressable disabled={!canOpen} onPress={() => event.prestamo_id && router.push({ pathname: '/prestamo/[id]', params: { id: event.prestamo_id } })} style={({ pressed }) => [styles.eventRow, pressed && styles.eventPressed]}><View style={styles.rail}><View style={[styles.eventIcon, { backgroundColor: visual.soft }]}><Ionicons color={visual.color} name={visual.icon} size={18} /></View>{!isLast ? <View style={styles.railLine} /> : null}</View><View style={styles.eventBody}><View style={styles.eventTop}><View style={styles.eventHeading}><View style={styles.titleLine}><Text numberOfLines={1} style={[styles.eventTitle, event.esta_revertido && styles.eventMuted]}>{eventTitle(event)}</Text>{event.esta_revertido ? <View style={styles.revertedBadge}><Text style={styles.revertedText}>Revertido</Text></View> : null}</View><Text style={styles.eventMeta}>{date}{event.cliente_nombre ? ` · ${event.cliente_nombre}` : ` · ${titleCase(event.medio)}`}</Text></View><View style={styles.amountColumn}><Text style={[styles.eventAmount, { color: visual.color }, event.esta_revertido && styles.eventMuted]}>{sign}{formatMoneyText(mainAmount, true)}</Text>{event.tipo === 'RENOVACION' ? <Text style={styles.amountCaption}>nuevo monto</Text> : isClosure ? <Text style={styles.amountCaption}>saldo afectado</Text> : null}</View></View>{event.tipo === 'RENOVACION' ? <View style={styles.breakdown}><DetailPill icon="swap-horizontal-outline" label={`Compensó ${formatMoneyText(event.saldo_compensado ?? '0.00', true)}`} /><DetailPill icon="paper-plane-outline" label={`Entregó ${formatMoneyText(event.monto_desembolsado ?? '0.00', true)}`} /></View> : null}{event.tipo === 'PRESTAMO_CREADO' ? <Text style={styles.eventDetail}>Total a cobrar {formatMoneyText(event.total_a_cobrar ?? '0.00', true)} · interés {formatMoneyText(event.monto_interes ?? '0.00', true)}</Text> : null}{event.tipo === 'PAGO_RECIBIDO' || event.tipo === 'PAGO_REVERTIDO' ? <Text style={styles.eventDetail}>{titleCase(event.medio)} · interés proporcional {formatMoneyText(event.monto_interes ?? '0.00', true)}</Text> : null}{event.tipo === 'PRESTAMO_INCOBRABLE' ? <Text style={styles.eventDetail}>Salió de la cartera activa · Caja no cambió</Text> : null}{event.tipo === 'PRESTAMO_ANULADO' ? <Text style={styles.eventDetail}>Desembolso revertido en Caja: {formatMoneyText(event.monto_desembolsado ?? '0.00', true)}</Text> : null}{event.nota && (event.categoria === 'CAJA' || event.categoria === 'CIERRE') ? <Text numberOfLines={2} style={styles.eventDetail}>Motivo: {event.nota}</Text> : null}{canOpen ? <View style={styles.openHint}><Text style={styles.openHintText}>Ver préstamo</Text><Ionicons color={colors.primary} name="chevron-forward" size={13} /></View> : null}</View></Pressable>;
}

function DetailPill({ icon, label }: { icon: React.ComponentProps<typeof Ionicons>['name']; label: string }) { return <View style={styles.detailPill}><Ionicons color={colors.primary} name={icon} size={13} /><Text style={styles.detailPillText}>{label}</Text></View>; }
function eventTitle(event: ActivityEvent) { const labels: Record<ActivityEvent['tipo'], string> = { CAPITAL_INICIAL: 'Capital inicial', APORTE_CAPITAL: 'Aporte de capital', RETIRO_CAPITAL: 'Retiro de capital', REVERSO_CAJA: 'Reverso de Caja', PRESTAMO_CREADO: 'Préstamo creado', RENOVACION: 'Préstamo renovado', PAGO_RECIBIDO: 'Pago recibido', PAGO_REVERTIDO: 'Pago revertido', PRESTAMO_INCOBRABLE: 'Préstamo marcado incobrable', PRESTAMO_ANULADO: 'Registro de préstamo anulado' }; return labels[event.tipo]; }
function eventVisual(event: ActivityEvent): { icon: React.ComponentProps<typeof Ionicons>['name']; color: string; soft: string } {
  if (event.tipo === 'PRESTAMO_INCOBRABLE') return { icon: 'alert-circle-outline', color: colors.danger, soft: colors.dangerSoft };
  if (event.tipo === 'PRESTAMO_ANULADO') return { icon: 'close-circle-outline', color: colors.textMuted, soft: colors.surfaceSoft };
  if (event.tipo === 'RENOVACION') return { icon: 'refresh-outline', color: colors.primary, soft: colors.primarySoft };
  if (event.tipo === 'PRESTAMO_CREADO') return { icon: 'wallet-outline', color: colors.cyan, soft: '#E7F8FA' };
  if (event.tipo === 'PAGO_RECIBIDO') return { icon: 'cash-outline', color: colors.success, soft: colors.successSoft };
  if (event.tipo === 'PAGO_REVERTIDO' || event.tipo === 'REVERSO_CAJA') return { icon: 'return-up-back-outline', color: colors.warning, soft: colors.warningSoft };
  if (event.tipo === 'RETIRO_CAPITAL') return { icon: 'arrow-up-outline', color: colors.danger, soft: colors.dangerSoft };
  return { icon: event.tipo === 'CAPITAL_INICIAL' ? 'flag-outline' : 'arrow-down-outline', color: colors.primary, soft: colors.primarySoft };
}
function groupEvents(events: ActivityEvent[]) {
  const today = new Date(); const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1);
  const todayKey = localDateKey(today); const yesterdayKey = localDateKey(yesterday); const groups = new Map<string, ActivityEvent[]>();
  events.forEach((event) => { const key = localDateKey(new Date(event.ocurrido_at)); groups.set(key, [...(groups.get(key) ?? []), event]); });
  return [...groups.entries()].map(([key, items]) => ({ key, label: key === todayKey ? 'Hoy' : key === yesterdayKey ? 'Ayer' : new Intl.DateTimeFormat('es-PE', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(items[0].ocurrido_at)), events: items }));
}
function localDateKey(value: Date) { return `${value.getFullYear()}-${value.getMonth() + 1}-${value.getDate()}`; }
function titleCase(value: string) { return value.charAt(0) + value.slice(1).toLocaleLowerCase('es-PE'); }
function normalize(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('es-PE'); }

const styles = StyleSheet.create({
  hero: { minHeight: 132, borderRadius: radii.xl, backgroundColor: colors.navy, padding: spacing.xl, flexDirection: 'row', alignItems: 'center', gap: spacing.md, ...shadows.card }, heroIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#FFFFFF17', alignItems: 'center', justifyContent: 'center' }, heroCopy: { flex: 1, minWidth: 0 }, heroEyebrow: { color: '#AEBCE2', fontSize: 11, fontFamily: fonts.extraBold, letterSpacing: 1.1 }, heroTitle: { color: '#FFFFFF', fontSize: 19, fontFamily: fonts.extraBold, marginTop: 5 }, heroText: { color: '#C1C9DD', fontSize: 12, lineHeight: 18, fontFamily: fonts.regular, marginTop: 4 }, heroCount: { minWidth: 58, height: 58, borderRadius: 18, backgroundColor: '#FFFFFF12', alignItems: 'center', justifyContent: 'center' }, heroCountValue: { color: '#FFFFFF', fontSize: 18, fontFamily: fonts.extraBold }, heroCountLabel: { color: '#AEBCE2', fontSize: 10, fontFamily: fonts.medium, marginTop: 1 },
  controls: { backgroundColor: colors.surface, borderRadius: radii.xl, padding: spacing.lg, gap: spacing.md, ...shadows.card }, searchBox: { minHeight: 50, borderRadius: radii.md, backgroundColor: colors.surfaceSoft, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md }, searchInput: { flex: 1, color: colors.text, fontSize: 14, fontFamily: fonts.medium }, clearSearch: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' }, chips: { gap: spacing.sm, paddingRight: spacing.sm }, categoryChip: { minHeight: 38, paddingHorizontal: spacing.md, borderRadius: radii.round, backgroundColor: colors.surfaceSoft, flexDirection: 'row', alignItems: 'center', gap: 6, borderWidth: 1, borderColor: colors.border }, categoryChipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, categoryText: { color: colors.textSecondary, fontSize: 12, fontFamily: fonts.bold }, categoryTextActive: { color: '#FFFFFF' }, mediumRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, mediumLabel: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.extraBold, textTransform: 'uppercase', letterSpacing: 0.8 }, mediumChips: { gap: 6, paddingRight: spacing.sm }, mediumChip: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: radii.round }, mediumChipActive: { backgroundColor: colors.primarySoft }, mediumText: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.semibold }, mediumTextActive: { color: colors.primary, fontFamily: fonts.extraBold },
  group: { gap: spacing.sm }, groupHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.xs }, groupTitle: { color: colors.text, fontSize: 17, fontFamily: fonts.extraBold, textTransform: 'capitalize' }, groupCount: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.medium }, timeline: { backgroundColor: colors.surface, borderRadius: radii.xl, paddingHorizontal: spacing.lg, ...shadows.card }, eventRow: { flexDirection: 'row', minHeight: 96 }, eventPressed: { opacity: 0.72 }, rail: { width: 44, alignItems: 'center', paddingTop: spacing.lg }, eventIcon: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', zIndex: 1 }, railLine: { width: 1.5, flex: 1, backgroundColor: colors.border, marginVertical: 4 }, eventBody: { flex: 1, minWidth: 0, paddingVertical: spacing.lg, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, eventTop: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, eventHeading: { flex: 1, minWidth: 0 }, titleLine: { flexDirection: 'row', alignItems: 'center', gap: 5 }, eventTitle: { color: colors.text, fontSize: 14, fontFamily: fonts.extraBold, flexShrink: 1 }, eventMeta: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.medium, marginTop: 4 }, amountColumn: { alignItems: 'flex-end' }, eventAmount: { fontSize: 14, fontFamily: fonts.extraBold, fontVariant: ['tabular-nums'] }, amountCaption: { color: colors.textMuted, fontSize: 10, fontFamily: fonts.medium, marginTop: 2 }, eventDetail: { color: colors.textSecondary, fontSize: 11, lineHeight: 17, fontFamily: fonts.regular, marginTop: spacing.sm }, eventMuted: { opacity: 0.42 }, breakdown: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: spacing.sm }, detailPill: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 6, borderRadius: radii.round, backgroundColor: colors.primarySoft }, detailPillText: { color: colors.primaryDark, fontSize: 10, fontFamily: fonts.bold }, openHint: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 7 }, openHintText: { color: colors.primary, fontSize: 10, fontFamily: fonts.bold }, revertedBadge: { paddingHorizontal: 6, paddingVertical: 3, borderRadius: radii.round, backgroundColor: colors.surfaceSoft }, revertedText: { color: colors.textMuted, fontSize: 10, fontFamily: fonts.bold },
  state: { minHeight: 300, borderRadius: radii.xl, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', padding: spacing.xxl, gap: spacing.sm, ...shadows.card }, stateIcon: { width: 58, height: 58, borderRadius: 20, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.sm }, errorIcon: { backgroundColor: colors.dangerSoft }, stateTitle: { color: colors.text, fontSize: 17, fontFamily: fonts.extraBold, textAlign: 'center' }, stateText: { color: colors.textSecondary, fontSize: 14, lineHeight: 22, fontFamily: fonts.regular, textAlign: 'center', maxWidth: 360 }, retryButton: { minHeight: 42, marginTop: spacing.sm, paddingHorizontal: spacing.xl, borderRadius: radii.round, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, retryText: { color: colors.primary, fontSize: 13, fontFamily: fonts.bold }, end: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.xxxl }, endLine: { flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: colors.border }, endIcon: { width: 30, height: 30, borderRadius: 10, backgroundColor: colors.surfaceSoft, alignItems: 'center', justifyContent: 'center' },
});
