import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AppScreen } from '@/components/app-screen';
import { colors, fonts, radii, shadows, spacing } from '@/constants/design';
import { getClientById } from '@/features/clientes/api';
import { getLoansSummary, type Loan } from '@/features/prestamos/api';
import { formatMoneyText, formatPercentageText } from '@/utils/money';

type HistoryFilter = 'TODOS' | 'PAGADO' | 'RENOVADO' | 'OTROS';

const filters: { value: HistoryFilter; label: string }[] = [
  { value: 'TODOS', label: 'Todos' },
  { value: 'PAGADO', label: 'Pagados' },
  { value: 'RENOVADO', label: 'Renovados' },
  { value: 'OTROS', label: 'Otros cierres' },
];

export default function ClientHistoryScreen() {
  const { id = '' } = useLocalSearchParams<{ id?: string }>();
  const [filter, setFilter] = useState<HistoryFilter>('TODOS');
  const clientQuery = useQuery({ queryKey: ['clientes', id], queryFn: () => getClientById(id), enabled: Boolean(id) });
  const loansQuery = useQuery({ queryKey: ['prestamos', 'cliente', id], queryFn: () => getLoansSummary(id), enabled: Boolean(id) });
  const historical = useMemo(() => (loansQuery.data?.prestamos ?? []).filter((loan) => loan.estado !== 'ACTIVO'), [loansQuery.data?.prestamos]);
  const filtered = useMemo(() => historical.filter((loan) => filter === 'TODOS' || loan.estado === filter || (filter === 'OTROS' && (loan.estado === 'INCOBRABLE' || loan.estado === 'ANULADO'))), [filter, historical]);
  const grouped = useMemo(() => {
    const groups = new Map<string, Loan[]>();
    filtered.forEach((loan) => {
      const year = new Date(loan.fecha_prestamo).getFullYear().toString();
      groups.set(year, [...(groups.get(year) ?? []), loan]);
    });
    return [...groups.entries()].sort(([a], [b]) => Number(b) - Number(a));
  }, [filtered]);
  const paidCount = historical.filter((loan) => loan.estado === 'PAGADO').length;
  const renewedCount = historical.filter((loan) => loan.estado === 'RENOVADO').length;
  const initials = clientQuery.data ? `${clientQuery.data.nombres.at(0) ?? ''}${clientQuery.data.apellidos?.at(0) ?? ''}`.toUpperCase() : '';

  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.topBar}><Pressable accessibilityLabel="Volver" onPress={() => router.back()} style={styles.topButton}><Ionicons color={colors.text} name="chevron-back" size={23} /></Pressable><Text style={styles.topTitle}>Historial del cliente</Text><View style={styles.topButton} /></View><AppScreen desktopNav={false} safeTop={false}>
    {clientQuery.isPending || loansQuery.isPending ? <View style={styles.state}><ActivityIndicator color={colors.primary} size="large" /><Text style={styles.stateText}>Abriendo el archivo…</Text></View> : null}
    {clientQuery.isError || loansQuery.isError ? <View style={styles.state}><View style={styles.errorIcon}><Ionicons color={colors.danger} name="cloud-offline-outline" size={28} /></View><Text style={styles.stateTitle}>No pudimos abrir el historial</Text><Text style={styles.stateText}>{clientQuery.error?.message ?? loansQuery.error?.message}</Text><Pressable onPress={() => { clientQuery.refetch(); loansQuery.refetch(); }} style={styles.retry}><Text style={styles.retryText}>Reintentar</Text></Pressable></View> : null}
    {clientQuery.data && loansQuery.data ? <>
      <View style={styles.hero}><View style={styles.heroOrbit} /><View style={styles.heroTop}><View style={styles.archiveIcon}><Ionicons color="#FFFFFF" name="albums" size={24} /></View><View style={styles.heroCopy}><Text style={styles.heroEyebrow}>ARCHIVO FINANCIERO</Text><Text numberOfLines={1} style={styles.heroName}>{clientQuery.data.nombres} {clientQuery.data.apellidos}</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View></View><View style={styles.heroCountRow}><Text style={styles.heroCount}>{historical.length}</Text><Text style={styles.heroCountLabel}>{historical.length === 1 ? 'operación cerrada' : 'operaciones cerradas'}</Text></View><View style={styles.heroStats}><HistoryStat color="#AFA4FF" label="Pagados" value={paidCount} /><View style={styles.statRule} /><HistoryStat color="#FFD18B" label="Renovados" value={renewedCount} /><View style={styles.statRule} /><HistoryStat color="#88E7D1" label="Otros" value={historical.length - paidCount - renewedCount} /></View></View>

      <View style={styles.filterSection}><View><Text style={styles.sectionTitle}>Movimientos anteriores</Text><Text style={styles.sectionSubtitle}>Selecciona uno para ver toda su trazabilidad</Text></View><ScrollView contentContainerStyle={styles.filters} horizontal showsHorizontalScrollIndicator={false}>{filters.map((item) => { const active = filter === item.value; return <Pressable accessibilityRole="button" key={item.value} onPress={() => setFilter(item.value)} style={[styles.filter, active && styles.filterActive]}><Text style={[styles.filterText, active && styles.filterTextActive]}>{item.label}</Text></Pressable>; })}</ScrollView></View>

      {grouped.map(([year, loans]) => <View key={year} style={styles.yearGroup}><View style={styles.yearHeader}><Text style={styles.year}>{year}</Text><Text style={styles.yearCount}>{loans.length} {loans.length === 1 ? 'préstamo' : 'préstamos'}</Text></View>{loans.map((loan) => <HistoryLoanCard key={loan.id} loan={loan} />)}</View>)}
      {filtered.length === 0 ? <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons color={colors.primary} name="albums-outline" size={28} /></View><Text style={styles.stateTitle}>{historical.length ? 'No hay préstamos en esta categoría' : 'El historial está vacío'}</Text><Text style={styles.stateText}>{historical.length ? 'Prueba seleccionando otro tipo de cierre.' : 'Cuando finalice o renueve un préstamo, aparecerá aquí automáticamente.'}</Text>{historical.length ? <Pressable onPress={() => setFilter('TODOS')} style={styles.retry}><Text style={styles.retryText}>Ver todo</Text></Pressable> : null}</View> : null}
      <View style={styles.auditNote}><Ionicons color={colors.primary} name="shield-checkmark-outline" size={18} /><Text style={styles.auditText}>Nada se elimina: pagos, compensaciones y reversos siguen conectados a cada préstamo.</Text></View>
    </> : null}
  </AppScreen></SafeAreaView>;
}

function HistoryStat({ value, label, color }: { value: number; label: string; color: string }) { return <View style={styles.stat}><View style={[styles.statDot, { backgroundColor: color }]} /><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }

function HistoryLoanCard({ loan }: { loan: Loan }) {
  const visual = loan.estado === 'PAGADO' ? { color: colors.primary, soft: colors.primarySoft, icon: 'checkmark-circle-outline' as const, label: 'Pagado' }
    : loan.estado === 'RENOVADO' ? { color: colors.warning, soft: colors.warningSoft, icon: 'refresh-outline' as const, label: 'Renovado' }
      : loan.estado === 'INCOBRABLE' ? { color: colors.danger, soft: colors.dangerSoft, icon: 'alert-circle-outline' as const, label: 'Incobrable' }
        : { color: colors.textMuted, soft: colors.surfaceSoft, icon: 'close-circle-outline' as const, label: 'Anulado' };
  const date = new Intl.DateTimeFormat('es-PE', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(loan.fecha_prestamo));
  const resultLabel = loan.estado === 'PAGADO' ? 'Total recuperado' : loan.estado === 'RENOVADO' ? 'Total compensado/cobrado' : loan.estado === 'INCOBRABLE' ? 'Saldo no recuperado' : 'Saldo vigente';
  const resultValue = loan.estado === 'PAGADO' || loan.estado === 'RENOVADO' ? loan.total_pagado : loan.saldo_pendiente;
  return <Pressable onPress={() => router.push({ pathname: '/prestamo/[id]', params: { id: loan.id } })} style={({ pressed }) => [styles.loanCard, pressed && styles.pressed]}><View style={[styles.loanAccent, { backgroundColor: visual.color }]} /><View style={styles.loanTop}><View style={[styles.loanIcon, { backgroundColor: visual.soft }]}><Ionicons color={visual.color} name={visual.icon} size={21} /></View><View style={styles.loanHeading}><Text style={styles.loanTitle}>{loan.tipo === 'RENOVACION' ? 'Renovación' : 'Préstamo'} de {formatMoneyText(loan.monto_base, true)}</Text><Text style={styles.loanDate}>{date} · {loan.numero_cuotas} cuotas</Text></View><View style={[styles.status, { backgroundColor: visual.soft }]}><Text style={[styles.statusText, { color: visual.color }]}>{visual.label}</Text></View></View><View style={styles.loanRule} /><View style={styles.loanNumbers}><View><Text style={styles.numberLabel}>{resultLabel}</Text><Text style={[styles.resultAmount, { color: visual.color }]}>{formatMoneyText(resultValue, true)}</Text></View><View style={styles.numberRight}><Text style={styles.numberLabel}>Interés aplicado</Text><Text style={styles.interest}>{formatPercentageText(loan.porcentaje_interes)}</Text></View></View><View style={styles.loanFooter}><Text style={styles.loanFooterText}>Total a cobrar {formatMoneyText(loan.total_a_cobrar, true)}</Text><View style={styles.openLoan}><Text style={styles.openLoanText}>Ver detalle</Text><Ionicons color={colors.primary} name="arrow-forward" size={14} /></View></View></Pressable>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background }, topBar: { width: '100%', maxWidth: 1080, alignSelf: 'center', minHeight: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border }, topButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, topTitle: { color: colors.text, fontSize: 18, fontFamily: fonts.extraBold },
  state: { minHeight: 360, borderRadius: radii.xl, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', gap: spacing.md, padding: spacing.xxl, ...shadows.card }, stateTitle: { color: colors.text, fontSize: 17, fontFamily: fonts.extraBold, textAlign: 'center' }, stateText: { color: colors.textSecondary, fontSize: 13, lineHeight: 20, fontFamily: fonts.regular, textAlign: 'center', maxWidth: 370 }, errorIcon: { width: 58, height: 58, borderRadius: 20, backgroundColor: colors.dangerSoft, alignItems: 'center', justifyContent: 'center' }, retry: { minHeight: 42, paddingHorizontal: spacing.xl, borderRadius: radii.round, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, retryText: { color: colors.primary, fontSize: 13, fontFamily: fonts.bold },
  hero: { minHeight: 226, borderRadius: radii.xl, backgroundColor: colors.navy, padding: spacing.xl, overflow: 'hidden', ...shadows.card }, heroOrbit: { position: 'absolute', width: 230, height: 230, borderRadius: 115, borderWidth: 1, borderColor: '#FFFFFF13', right: -68, top: -90 }, heroTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, archiveIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#FFFFFF18', alignItems: 'center', justifyContent: 'center' }, heroCopy: { flex: 1, minWidth: 0 }, heroEyebrow: { color: '#AEBCE2', fontSize: 10, fontFamily: fonts.extraBold, letterSpacing: 1.1 }, heroName: { color: '#FFFFFF', fontSize: 16, fontFamily: fonts.extraBold, marginTop: 5 }, avatar: { width: 38, height: 38, borderRadius: 13, backgroundColor: '#FFFFFF18', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#FFFFFF', fontSize: 13, fontFamily: fonts.extraBold }, heroCountRow: { flexDirection: 'row', alignItems: 'baseline', gap: spacing.sm, marginTop: spacing.xl }, heroCount: { color: '#FFFFFF', fontSize: 36, fontFamily: fonts.extraBold, fontVariant: ['tabular-nums'] }, heroCountLabel: { color: '#C2CAE0', fontSize: 13, fontFamily: fonts.medium }, heroStats: { minHeight: 54, flexDirection: 'row', alignItems: 'center', marginTop: 'auto', paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: '#FFFFFF18' }, stat: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, statDot: { width: 5, height: 5, borderRadius: 3 }, statValue: { color: '#FFFFFF', fontSize: 13, fontFamily: fonts.extraBold }, statLabel: { color: '#AEB8D2', fontSize: 10, fontFamily: fonts.medium }, statRule: { width: 1, height: 22, backgroundColor: '#FFFFFF1A' },
  filterSection: { gap: spacing.md }, sectionTitle: { color: colors.text, fontSize: 16, fontFamily: fonts.extraBold }, sectionSubtitle: { color: colors.textMuted, fontSize: 12, fontFamily: fonts.regular, marginTop: 3 }, filters: { gap: spacing.sm, paddingRight: spacing.lg }, filter: { minHeight: 39, paddingHorizontal: spacing.lg, borderRadius: radii.round, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, filterActive: { backgroundColor: colors.primary, borderColor: colors.primary }, filterText: { color: colors.textSecondary, fontSize: 12, fontFamily: fonts.bold }, filterTextActive: { color: '#FFFFFF' },
  yearGroup: { gap: spacing.md }, yearHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.xs }, year: { color: colors.text, fontSize: 17, fontFamily: fonts.extraBold }, yearCount: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.medium }, loanCard: { backgroundColor: colors.surface, borderRadius: radii.xl, padding: spacing.lg, overflow: 'hidden', ...shadows.card }, pressed: { opacity: 0.75, transform: [{ scale: 0.995 }] }, loanAccent: { position: 'absolute', left: 0, top: spacing.xl, bottom: spacing.xl, width: 3, borderTopRightRadius: 3, borderBottomRightRadius: 3 }, loanTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, loanIcon: { width: 43, height: 43, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, loanHeading: { flex: 1, minWidth: 0 }, loanTitle: { color: colors.text, fontSize: 15, fontFamily: fonts.extraBold }, loanDate: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.medium, marginTop: 4 }, status: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: radii.round }, statusText: { fontSize: 11, fontFamily: fonts.bold }, loanRule: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border, marginVertical: spacing.md }, loanNumbers: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: spacing.md }, numberLabel: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.medium }, resultAmount: { fontSize: 18, fontFamily: fonts.extraBold, marginTop: 4, fontVariant: ['tabular-nums'] }, numberRight: { alignItems: 'flex-end' }, interest: { color: colors.text, fontSize: 15, fontFamily: fonts.bold, marginTop: 5 }, loanFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm, marginTop: spacing.md }, loanFooterText: { color: colors.textSecondary, fontSize: 11, fontFamily: fonts.medium }, openLoan: { flexDirection: 'row', alignItems: 'center', gap: 4 }, openLoanText: { color: colors.primary, fontSize: 11, fontFamily: fonts.bold },
  empty: { minHeight: 260, borderRadius: radii.xl, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', padding: spacing.xxl, gap: spacing.sm, ...shadows.card }, emptyIcon: { width: 60, height: 60, borderRadius: 21, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.sm }, auditNote: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderRadius: radii.md, backgroundColor: colors.primarySoft, padding: spacing.md }, auditText: { flex: 1, color: colors.primaryDark, fontSize: 11, lineHeight: 17, fontFamily: fonts.medium },
});
