import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, LayoutAnimation, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AppScreen } from '@/components/app-screen';
import { colors, fonts, radii, shadows, spacing } from '@/constants/design';
import { getLoanClosure, getLoansSummary, type LoanPayment } from '@/features/prestamos/api';
import { formatMoneyText, formatPercentageText } from '@/utils/money';

export default function LoanDetailScreen() {
  const { id = '' } = useLocalSearchParams<{ id?: string }>();
  const [conditionsExpanded, setConditionsExpanded] = useState(true);
  const [installmentsExpanded, setInstallmentsExpanded] = useState(true);
  const loansQuery = useQuery({ queryKey: ['prestamos'], queryFn: () => getLoansSummary() });
  const loan = loansQuery.data?.prestamos.find((item) => item.id === id);
  const isExceptionallyClosed = loan?.estado === 'INCOBRABLE' || loan?.estado === 'ANULADO';
  const closureQuery = useQuery({ queryKey: ['cierre-prestamo', id], queryFn: () => getLoanClosure(id), enabled: Boolean(id && isExceptionallyClosed) });
  const date = loan ? new Intl.DateTimeFormat('es-PE', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(loan.fecha_prestamo)) : '';
  const pendingInstallments = loan?.cuotas.filter((installment) => installment.estado !== 'PAGADA') ?? [];
  const renewalEligible = Boolean(loan && pendingInstallments.length === 1 && pendingInstallments[0].numero === loan.numero_cuotas);
  const installmentPlanAnnulled = loan?.estado === 'ANULADO';

  const statusVisual = loan?.estado === 'ACTIVO' ? { background: colors.successSoft, color: colors.success }
    : loan?.estado === 'PAGADO' ? { background: colors.primarySoft, color: colors.primary }
      : loan?.estado === 'RENOVADO' ? { background: colors.warningSoft, color: colors.warning }
        : loan?.estado === 'INCOBRABLE' ? { background: colors.dangerSoft, color: colors.danger }
          : { background: colors.surfaceSoft, color: colors.textMuted };

  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.topBar}><Pressable accessibilityLabel="Volver" onPress={() => router.back()} style={styles.topButton}><Ionicons color={colors.text} name="chevron-back" size={23} /></Pressable><Text style={styles.topTitle}>Detalle del préstamo</Text>{loan?.estado === 'ACTIVO' ? <Pressable accessibilityLabel="Opciones de cierre" onPress={() => router.push({ pathname: '/prestamo/cerrar', params: { prestamoId: loan.id } })} style={styles.topButton}><Ionicons color={colors.text} name="ellipsis-horizontal" size={22} /></Pressable> : <View style={styles.topButton} />}</View><AppScreen desktopNav={false} safeTop={false}>
    {loansQuery.isPending ? <View style={styles.state}><ActivityIndicator color={colors.primary} size="large" /></View> : null}
    {loansQuery.isError ? <View style={styles.state}><Ionicons color={colors.danger} name="alert-circle-outline" size={29} /><Text style={styles.stateTitle}>No pudimos cargar el préstamo</Text></View> : null}
    {loansQuery.isSuccess && !loan ? <View style={styles.state}><Text style={styles.stateTitle}>Préstamo no encontrado</Text></View> : null}
    {loan ? <>
      <View style={styles.profile}><View style={styles.profileIcon}><Ionicons color={colors.primary} name="person-outline" size={22} /></View><View style={styles.profileCopy}><Text style={styles.client}>{loan.cliente_nombre}</Text><Text style={styles.date}>Creado el {date}</Text></View><View style={[styles.status, { backgroundColor: statusVisual.background }]}><View style={[styles.statusDot, { backgroundColor: statusVisual.color }]} /><Text style={[styles.statusText, { color: statusVisual.color }]}>{loan.estado.charAt(0) + loan.estado.slice(1).toLowerCase()}</Text></View></View>
      <View style={styles.hero}><View style={styles.heroTop}><Text style={styles.heroLabel}>SALDO PENDIENTE</Text><Ionicons color="#FFFFFFB5" name="shield-checkmark-outline" size={19} /></View><Text style={styles.heroAmount}>{formatMoneyText(loan.saldo_pendiente, true)}</Text><View style={styles.heroRule} /><View style={styles.heroBottom}><View><Text style={styles.heroMiniLabel}>Total a cobrar</Text><Text style={styles.heroMiniValue}>{formatMoneyText(loan.total_a_cobrar, true)}</Text></View><View><Text style={styles.heroMiniLabel}>Interés</Text><Text style={styles.heroMiniValue}>{formatPercentageText(loan.porcentaje_interes)}</Text></View><View><Text style={styles.heroMiniLabel}>Cuotas</Text><Text style={styles.heroMiniValue}>{loan.numero_cuotas}</Text></View></View></View>
      {loan.estado === 'ACTIVO' ? <><View style={styles.actions}><Pressable onPress={() => router.push({ pathname: '/pago/nuevo', params: { prestamoId: loan.id } })} style={[styles.payButton, !renewalEligible && styles.payButtonWide]}><Ionicons color="#FFFFFF" name="cash-outline" size={20} /><Text style={styles.payButtonText}>Registrar pago</Text></Pressable>{renewalEligible ? <Pressable onPress={() => router.push({ pathname: '/prestamo/renovar', params: { prestamoId: loan.id } })} style={styles.renewButton}><Ionicons color={colors.primary} name="refresh" size={19} /><Text style={styles.renewButtonText}>Renovar</Text></Pressable> : null}</View>{!renewalEligible ? <View style={styles.renewalHint}><Ionicons color={colors.primary} name="information-circle-outline" size={16} /><Text style={styles.renewalHintText}>Podrás renovar cuando quede pendiente únicamente la última cuota.</Text></View> : null}</> : null}
      {loan.estado === 'ACTIVO' ? <Pressable onPress={() => router.push({ pathname: '/prestamo/cerrar', params: { prestamoId: loan.id } })} style={styles.closeOptions}><View style={styles.closeOptionsIcon}><Ionicons color={colors.textSecondary} name="shield-outline" size={18} /></View><View style={styles.closeOptionsCopy}><Text style={styles.closeOptionsTitle}>Opciones de cierre</Text><Text style={styles.closeOptionsText}>Incobrable o registro creado por error</Text></View><Ionicons color={colors.textMuted} name="chevron-forward" size={18} /></Pressable> : null}
      {isExceptionallyClosed && closureQuery.data ? <View style={[styles.closureCard, loan.estado === 'INCOBRABLE' ? styles.closureDanger : styles.closureNeutral]}><View style={styles.closureHeader}><View style={[styles.closureIcon, { backgroundColor: loan.estado === 'INCOBRABLE' ? colors.dangerSoft : colors.surfaceSoft }]}><Ionicons color={loan.estado === 'INCOBRABLE' ? colors.danger : colors.textSecondary} name={loan.estado === 'INCOBRABLE' ? 'alert-circle-outline' : 'close-circle-outline'} size={22} /></View><View style={styles.closureHeading}><Text style={styles.closureTitle}>{loan.estado === 'INCOBRABLE' ? 'Saldo declarado incobrable' : 'Registro anulado'}</Text><Text style={styles.closureDate}>{new Intl.DateTimeFormat('es-PE', { day: '2-digit', month: 'long', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(closureQuery.data.ocurrido_at))}</Text></View></View><Text style={styles.closureReason}>“{closureQuery.data.motivo}”</Text><View style={styles.closureRule} /><View style={styles.closureBottom}><View><Text style={styles.closureAmountLabel}>Saldo afectado</Text><Text style={styles.closureAmount}>{formatMoneyText(closureQuery.data.saldo_afectado, true)}</Text></View><View style={styles.closureImpact}><Ionicons color={loan.estado === 'INCOBRABLE' ? colors.textMuted : colors.success} name={loan.estado === 'INCOBRABLE' ? 'remove-outline' : 'return-up-back-outline'} size={15} /><Text style={styles.closureImpactText}>{loan.estado === 'INCOBRABLE' ? 'Caja sin cambios' : `${formatMoneyText(closureQuery.data.monto_caja_revertido, true)} a Caja`}</Text></View></View></View> : null}
      <View style={styles.detailCard}><Pressable accessibilityRole="button" accessibilityState={{ expanded: conditionsExpanded }} onPress={() => { LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut); setConditionsExpanded((expanded) => !expanded); }} style={({ pressed }) => [styles.collapsibleHeader, pressed && styles.headerPressed]}><Text style={styles.sectionTitle}>Condiciones del préstamo</Text><Ionicons color={colors.primary} name={conditionsExpanded ? 'chevron-up' : 'chevron-down'} size={19} /></Pressable>{conditionsExpanded ? <View><DetailRow label="Monto base" value={formatMoneyText(loan.monto_base, true)} /><DetailRow label="Monto entregado" value={formatMoneyText(loan.monto_desembolsado, true)} />{loan.tipo === 'RENOVACION' ? <DetailRow label="Saldo anterior compensado" value={formatMoneyText(loan.saldo_compensado, true)} /> : null}<DetailRow label="Interés calculado" value={formatMoneyText(loan.monto_interes, true)} /><DetailRow label="Total aplicado" value={formatMoneyText(loan.total_pagado, true)} /><DetailRow label="Medio de entrega" value={loan.medio_desembolso.charAt(0) + loan.medio_desembolso.slice(1).toLowerCase()} noBorder /></View> : null}</View>
      <View style={styles.installments}><Pressable accessibilityRole="button" accessibilityState={{ expanded: installmentsExpanded }} onPress={() => { LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut); setInstallmentsExpanded((expanded) => !expanded); }} style={({ pressed }) => [styles.collapsibleHeader, pressed && styles.headerPressed]}><View><Text style={styles.sectionTitle}>Plan de cuotas</Text>{installmentsExpanded ? <Text style={styles.sectionSubtitle}>{installmentPlanAnnulled ? 'Plan original conservado como referencia' : 'Sin fechas límite · se registra al pagar'}</Text> : null}</View><View style={styles.headerAside}>{installmentsExpanded ? <View style={styles.count}><Text style={styles.countText}>{loan.numero_cuotas}</Text></View> : null}<Ionicons color={colors.primary} name={installmentsExpanded ? 'chevron-up' : 'chevron-down'} size={19} /></View></Pressable>{installmentsExpanded ? loan.cuotas.map((installment) => <View key={installment.id} style={styles.installmentRow}><View style={[styles.installmentNumber, installment.estado === 'PAGADA' && styles.installmentPaid, installmentPlanAnnulled && styles.installmentAnnulled]}>{installmentPlanAnnulled ? <Ionicons color={colors.textMuted} name="close" size={17} /> : installment.estado === 'PAGADA' ? <Ionicons color="#FFFFFF" name="checkmark" size={17} /> : <Text style={styles.installmentNumberText}>{installment.numero}</Text>}</View><View style={styles.installmentCopy}><Text style={styles.installmentTitle}>Cuota {installment.numero}</Text><Text style={[styles.installmentState, installment.estado === 'PAGADA' && styles.installmentStatePaid, installment.estado === 'PARCIAL' && styles.installmentStatePartial, installmentPlanAnnulled && styles.installmentStateAnnulled]}>{installmentPlanAnnulled ? 'Anulada' : installment.estado === 'PAGADA' ? 'Pagada' : installment.estado === 'PARCIAL' ? `Parcial · falta ${formatMoneyText(installment.saldo_pendiente, true)}` : 'Pendiente'}</Text>{installment.monto_recibido_traslado !== '0.00' ? <Text style={styles.transferText}>Incluye {formatMoneyText(installment.monto_recibido_traslado, true)} trasladados</Text> : null}</View><View style={styles.installmentRight}><Text style={[styles.installmentAmount, installmentPlanAnnulled && styles.installmentAmountAnnulled]}>{formatMoneyText(installment.monto_actual, true)}</Text>{installment.monto_pagado !== '0.00' ? <Text style={styles.installmentPaidText}>{formatMoneyText(installment.monto_pagado, true)} recibido</Text> : null}</View></View>) : null}</View>
      {loan.pagos.length ? <View style={styles.paymentsCard}><View style={styles.paymentHeader}><View><Text style={styles.sectionTitle}>Historial de pagos</Text><Text style={styles.sectionSubtitle}>Capital e interés distribuidos proporcionalmente</Text></View><View style={styles.count}><Text style={styles.countText}>{loan.pagos.length}</Text></View></View>{loan.pagos.map((payment) => <PaymentRow key={payment.id} payment={payment} onPress={payment.tipo === 'PAGO' && !payment.esta_revertido && (loan.estado === 'ACTIVO' || loan.estado === 'PAGADO') ? () => router.push({ pathname: '/pago/revertir', params: { prestamoId: loan.id, pagoId: payment.id } }) : undefined} />)}</View> : null}
    </> : null}
  </AppScreen></SafeAreaView>;
}

function DetailRow({ label, value, noBorder = false }: { label: string; value: string; noBorder?: boolean }) { return <View style={[styles.detailRow, noBorder && styles.noBorder]}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }

function PaymentRow({ payment, onPress }: { payment: LoanPayment; onPress?: () => void }) {
  const reversed = payment.esta_revertido || payment.tipo === 'REVERSO';
  const compensation = payment.tipo === 'COMPENSACION_RENOVACION';
  const date = new Intl.DateTimeFormat('es-PE', { day: '2-digit', month: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date(payment.ocurrido_at));
  const installmentLabel = payment.tipo === 'COMPENSACION_RENOVACION' ? 'Compensación por renovación' : payment.tipo === 'REVERSO' ? 'Reverso de pago' : payment.cuotas.length > 1 ? 'Pago total' : payment.cuotas.length === 1 ? `Cuota ${payment.cuotas[0]}` : 'Pago';
  const meta = compensation ? `${date} · No ingresó efectivo` : `${date} · ${payment.medio.charAt(0) + payment.medio.slice(1).toLowerCase()}`;
  const iconName = payment.tipo === 'REVERSO' ? 'return-up-back-outline' : compensation ? 'swap-horizontal-outline' : 'cash-outline';
  const iconColor = reversed ? colors.textMuted : compensation ? colors.primary : colors.success;
  return <Pressable disabled={!onPress} onPress={onPress} style={styles.paymentRow}><View style={[styles.paymentIcon, compensation && styles.paymentIconCompensation, reversed && styles.paymentIconReversed]}><Ionicons color={iconColor} name={iconName} size={17} /></View><View style={styles.paymentCopy}><View style={styles.paymentTitleLine}><Text style={[styles.paymentTitle, reversed && styles.mutedPayment]}>{installmentLabel}</Text>{payment.esta_revertido ? <View style={styles.reversedBadge}><Text style={styles.reversedText}>Revertido</Text></View> : null}</View><Text style={styles.paymentMeta}>{meta}</Text>{payment.monto_trasladado !== '0.00' ? <Text style={styles.paymentTransfer}>Se trasladaron {formatMoneyText(payment.monto_trasladado, true)}</Text> : null}</View><View style={styles.paymentRight}><Text style={[styles.paymentAmount, compensation && styles.compensationAmount, reversed && styles.mutedPayment]}>{compensation ? '' : payment.direccion === -1 ? '− ' : '+ '}{formatMoneyText(payment.monto, true)}</Text>{onPress ? <Text style={styles.paymentAction}>Opciones</Text> : null}</View></Pressable>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background }, topBar: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border }, topButton: { width: 52, height: 52, alignItems: 'center', justifyContent: 'center' }, topTitle: { color: colors.text, fontSize: 17, fontFamily: fonts.extraBold }, state: { minHeight: 320, backgroundColor: colors.surface, borderRadius: radii.xl, alignItems: 'center', justifyContent: 'center', gap: spacing.md }, stateTitle: { color: colors.text, fontSize: 16, fontFamily: fonts.extraBold },
  profile: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, profileIcon: { width: 50, height: 50, borderRadius: 17, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, profileCopy: { flex: 1 }, client: { color: colors.text, fontSize: 18, fontFamily: fonts.extraBold }, date: { color: colors.textMuted, fontSize: 12, fontFamily: fonts.regular, marginTop: 4 }, status: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: radii.round }, statusDot: { width: 6, height: 6, borderRadius: 3 }, statusText: { fontSize: 12, fontFamily: fonts.bold },
  hero: { backgroundColor: colors.navy, borderRadius: radii.xl, padding: spacing.xxl, ...shadows.card }, heroTop: { flexDirection: 'row', justifyContent: 'space-between' }, heroLabel: { color: '#FFFFFFA3', fontSize: 12, fontFamily: fonts.extraBold, letterSpacing: 1 }, heroAmount: { color: '#FFFFFF', fontSize: 36, fontFamily: fonts.extraBold, marginTop: spacing.sm, fontVariant: ['tabular-nums'] }, heroRule: { height: 1, backgroundColor: '#FFFFFF1F', marginVertical: spacing.lg }, heroBottom: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md }, heroMiniLabel: { color: '#FFFFFF8F', fontSize: 11, fontFamily: fonts.medium }, heroMiniValue: { color: '#FFFFFF', fontSize: 15, fontFamily: fonts.bold, marginTop: 3 },
  detailCard: { backgroundColor: colors.surface, borderRadius: radii.xl, paddingHorizontal: spacing.xl, ...shadows.card }, sectionTitle: { color: colors.text, fontSize: 18, fontFamily: fonts.extraBold }, sectionSubtitle: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.regular, marginTop: 3 }, collapsibleHeader: { minHeight: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md }, headerAside: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, headerPressed: { opacity: 0.64 }, detailRow: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, noBorder: { borderBottomWidth: 0 }, detailLabel: { color: colors.textSecondary, fontSize: 13, fontFamily: fonts.medium }, detailValue: { color: colors.text, fontSize: 14, fontFamily: fonts.bold },
  actions: { flexDirection: 'row', gap: spacing.sm }, payButton: { flex: 1.35, minHeight: 55, borderRadius: radii.md, backgroundColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, ...shadows.card }, payButtonWide: { flex: 1 }, payButtonText: { color: '#FFFFFF', fontSize: 14, fontFamily: fonts.bold }, renewButton: { flex: 1, minHeight: 55, borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: 1.5, borderColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, renewButtonText: { color: colors.primary, fontSize: 14, fontFamily: fonts.bold }, renewalHint: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderRadius: radii.md, backgroundColor: colors.primarySoft, paddingHorizontal: spacing.lg, paddingVertical: spacing.md }, renewalHintText: { flex: 1, color: colors.primary, fontSize: 12, lineHeight: 18, fontFamily: fonts.medium },
  closeOptions: { minHeight: 66, borderRadius: radii.lg, backgroundColor: colors.surface, paddingHorizontal: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderWidth: 1, borderColor: colors.border }, closeOptionsIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: colors.surfaceSoft, alignItems: 'center', justifyContent: 'center' }, closeOptionsCopy: { flex: 1 }, closeOptionsTitle: { color: colors.text, fontSize: 13, fontFamily: fonts.bold }, closeOptionsText: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.regular, marginTop: 3 },
  closureCard: { borderRadius: radii.xl, backgroundColor: colors.surface, padding: spacing.xl, borderWidth: 1, ...shadows.card }, closureDanger: { borderColor: '#F6CDD2' }, closureNeutral: { borderColor: colors.border }, closureHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, closureIcon: { width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, closureHeading: { flex: 1 }, closureTitle: { color: colors.text, fontSize: 16, fontFamily: fonts.extraBold }, closureDate: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.medium, marginTop: 3 }, closureReason: { color: colors.textSecondary, fontSize: 13, lineHeight: 20, fontFamily: fonts.medium, marginTop: spacing.lg }, closureRule: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border, marginVertical: spacing.lg }, closureBottom: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: spacing.md }, closureAmountLabel: { color: colors.textMuted, fontSize: 11, fontFamily: fonts.medium }, closureAmount: { color: colors.text, fontSize: 17, fontFamily: fonts.extraBold, marginTop: 3, fontVariant: ['tabular-nums'] }, closureImpact: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.surfaceSoft, borderRadius: radii.round, paddingHorizontal: 9, paddingVertical: 6 }, closureImpactText: { color: colors.textSecondary, fontSize: 11, fontFamily: fonts.bold },
  installments: { backgroundColor: colors.surface, borderRadius: radii.xl, paddingHorizontal: spacing.xl, ...shadows.card }, count: { width: 31, height: 31, borderRadius: 10, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, countText: { color: colors.primary, fontSize: 13, fontFamily: fonts.extraBold }, installmentRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }, installmentNumber: { width: 34, height: 34, borderRadius: 11, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, installmentPaid: { backgroundColor: colors.success }, installmentAnnulled: { backgroundColor: colors.surfaceSoft }, installmentNumberText: { color: colors.primary, fontSize: 13, fontFamily: fonts.extraBold }, installmentCopy: { flex: 1 }, installmentTitle: { color: colors.text, fontSize: 14, fontFamily: fonts.bold }, installmentState: { color: colors.warning, fontSize: 11, fontFamily: fonts.medium, marginTop: 3 }, installmentStatePaid: { color: colors.success }, installmentStatePartial: { color: colors.warning }, installmentStateAnnulled: { color: colors.textMuted }, transferText: { color: colors.primary, fontSize: 10, fontFamily: fonts.medium, marginTop: 3 }, installmentRight: { alignItems: 'flex-end' }, installmentAmount: { color: colors.text, fontSize: 15, fontFamily: fonts.extraBold, fontVariant: ['tabular-nums'] }, installmentAmountAnnulled: { color: colors.textMuted, textDecorationLine: 'line-through' }, installmentPaidText: { color: colors.textMuted, fontSize: 10, fontFamily: fonts.medium, marginTop: 3 },
  paymentsCard: { backgroundColor: colors.surface, borderRadius: radii.xl, paddingHorizontal: spacing.xl, ...shadows.card }, paymentHeader: { minHeight: 76, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, paymentRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }, paymentIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: colors.successSoft, alignItems: 'center', justifyContent: 'center' }, paymentIconCompensation: { backgroundColor: colors.primarySoft }, paymentIconReversed: { backgroundColor: colors.surfaceSoft }, paymentCopy: { flex: 1, minWidth: 0 }, paymentTitleLine: { flexDirection: 'row', alignItems: 'center', gap: 5 }, paymentTitle: { color: colors.text, fontSize: 13, fontFamily: fonts.bold }, paymentMeta: { color: colors.textMuted, fontSize: 10, fontFamily: fonts.regular, marginTop: 3 }, paymentTransfer: { color: colors.primary, fontSize: 10, fontFamily: fonts.medium, marginTop: 3 }, paymentRight: { alignItems: 'flex-end' }, paymentAmount: { color: colors.success, fontSize: 14, fontFamily: fonts.extraBold, fontVariant: ['tabular-nums'] }, compensationAmount: { color: colors.primary }, paymentAction: { color: colors.primary, fontSize: 10, fontFamily: fonts.bold, marginTop: 4 }, mutedPayment: { color: colors.textMuted }, reversedBadge: { borderRadius: radii.round, backgroundColor: colors.surfaceSoft, paddingHorizontal: 6, paddingVertical: 3 }, reversedText: { color: colors.textMuted, fontSize: 10, fontFamily: fonts.bold },
});
